### ISSUE TITLE
Does not compile with Boost Test 1.67

### ISSUE THREAD

**Issue by yuchdev** [JetBrains/teamcity-cpp#25]
Compiler MSVS 2015 VC++ 14.0
Boost Test 1.67

teamcity_boost.cpp(78): error C2259: 'JetBrains::TeamcityBoostLogFormatter': cannot instantiate abstract class
teamcity_boost.cpp(78): note: due to following members:
teamcity_boost.cpp(78): note: 'void boost::unit_test::unit_test_log_formatter::log_entry_context(std::ostream &,boost::unit_test::log_level,boost::unit_test::const_string)': is abstract
boost/test/unit_test_log_formatter.hpp(267): note: see declaration of 'boost::unit_test::unit_test_log_formatter::log_entry_context'
teamcity_boost.cpp(78): note: 'void boost::unit_test::unit_test_log_formatter::entry_context_finish(std::ostream &,boost::unit_test::log_level)': is abstract
unit_test_log_formatter.hpp(274): note: see declaration of 'boost::unit_test::unit_test_log_formatter::entry_context_finish'

**Comment by k15tfu** [comment]
@dmitry-treskunov Fixed by https://github.com/JetBrains/teamcity-cpp/commit/6620272df69790f0e7fcce35d2f4c7bdef57e58e. You can close it.
